version: '3.7'
services:
    web:
        image: architecture_web
        container_name: architecture_web
        restart: always
        build:
            context: .
            dockerfile: dockerfile
        # environment:
        # - Database=Database
        depends_on:
            - database
        networks:
            - network
        ports:
            - 8090:80
    database:
        image: mongo
        container_name: architecture_database
        restart: always
        environment:
            - TZ=America/Sao_Paulo
        networks:
            - network
        ports:
            - 27017:27017
        volumes:
            - database:/var/opt/data

networks:
    network:
volumes:
    database:
