version: '3.7'

volumes:
  init-db:
  data-db:

services:
  hacking-mongodb:
    image: mongo
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: keep_hacking
    ports:
      - 27017:27017

  hacking-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin

  hacking-web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/keep_hacking
    ports:
      - 8000:8000
    links:
      - hacking-mongodb
    depends_on:
      - hacking-migration

  hacking-migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/keep_hacking
    links:
      - hacking-mongodb
    depends_on:
      - hacking-make-migrations

  hacking-make-migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/keep_hacking
    links:
      - hacking-mongodb
    depends_on:
      - hacking-mongodb

volumes:
  init-db:
  data-db:

networks:
  default:
    external:
      name: keep-hacking-network
